{% set name = "hodl" %}
{% set version = "1.0" %}
{% set about = "Higher level language for writing oracles for quantum computers" %}
{% set git_rev = " https://github.com/at2005/HODL/releases/" %}
{% set git_url = " https://github.com/at2005/HODL.git" %}
{% set script = "python setup.py install" %}
{% set outp = "qc" %}

package:
  name: "hodl"
  version: "1.0.0"


source:
#  git_rev: v1
#  git_url: https://github.com/at2005/HODL
  path: ../

requirements:
  host:
    - python
  build:
    - python
    - {{ compiler('cxx') }}
 

about:
  home: https://github.com/at2005/HODL
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "{{ about }}"

