
# name: HODL-build

# on: [push]

# env:
#   GITHUB_ACTIONS: true

# jobs:
# #linux build
#    build-and-test-linux:
#       runs-on: ubuntu-latest
#       steps:
#          - uses: actions/checkout@v3
#          - run: mkdir bin
#          - run: make
#          - run: bin/hodl --target qasm -o out.qasm data/grover.hodl
#    build-and-test-macos:
#       runs-on: macos-latest
#       steps:
#          - uses: actions/checkout@v3
#          - run: mkdir bin
#          - run: make
#          - run: bin/hodl --target qasm -o out.qasm data/grover.hodl

name: HODL Compile and Run
on:
  push:
    branches:
      - master

env:
  GITHUB_ACTIONS: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Setup GCC
    #   uses: actions/setup-mingw@v1
    #   with:
    #     version: '9.3.0'
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2.2.0


    - name: Create bin directory
      run: |
        mkdir bin

    - name: Compile C++ file
      run: |
        g++ -std=c++11 src/compiler/source.cpp src/circuit/circuit.cpp -o bin/hodl.exe

    - name: Run compiled binary
      run: |
        ./bin/hodl.exe --target qasm -o out.qasm data/grover.hodl
    - name: Test QASM File
      run: |
        cat out.qasm

