
# name: HODL-build

# on: [push]

# jobs:
# #linux build
#    build-and-test-linux:
#       runs-on: ubuntu-latest
#       steps:
#          - uses: actions/checkout@v3
#          - run: mkdir bin
#          - run: make
#          - run: bin/hodl --target qasm -o out.qasm data/grover.hodl
#    build-and-test-macos:
#       runs-on: macos-latest
#       steps:
#          - uses: actions/checkout@v3
#          - run: mkdir bin
#          - run: make
#          - run: bin/hodl --target qasm -o out.qasm data/grover.hodl


name: HODL-build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build & test HODL on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [ g++-11 ]
        include:
          - os: ubuntu-latest
            compiler: g++-11
            target: Linux

          - os: macos-latest
            compiler: g++-11
            target: Macos

          - os: windows-latest
            compiler: cl
            target: Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Compile a release build of HODL
        run: mkdir bin; ${{ matrix.compiler }} -std=c++11 -o bin/hodl src/compiler/*.cpp src/circuit/*.cpp
         # run: bin/hodl --target qasm -o out.qasm data/grover.hodl
 
      # - name: Run HODL tests
      #   run: ./scripts/run_all_tests.sh --build Release --os ${{ matrix.target }}

