
# name: HODL-build

# on: [push]

# env:
#   GITHUB_ACTIONS: true

# jobs:
# #linux build
#    build-and-test-linux:
#       runs-on: ubuntu-latest
#       steps:
#          - uses: actions/checkout@v3
#          - run: mkdir bin
#          - run: make
#          - run: bin/hodl --target qasm -o out.qasm data/grover.hodl
#    build-and-test-macos:
#       runs-on: macos-latest
#       steps:
#          - uses: actions/checkout@v3
#          - run: mkdir bin
#          - run: make
#          - run: bin/hodl --target qasm -o out.qasm data/grover.hodl

name: HODL Compile and Run
on:
  push:
    branches:
      - master

env:
  GITHUB_ACTIONS: true

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Setup GCC
    #   uses: actions/setup-mingw@v1
    #   with:
    #     version: '9.3.0'
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2.2.0


    - name: Create bin directory
      run: |
        mkdir bin

    - name: Compile C++ file
      run: |
        g++ -std=c++11 src/compiler/source.cpp src/circuit/circuit.cpp -o bin/hodl.exe

    - name: Run compiled binary
      run: |
        ./bin/hodl.exe --target qasm -o out.qasm data/grover.hodl


  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create bin directory
      run: |
        mkdir bin

    - name: Compile C++ file
      run: |
        g++ -std=c++11 src/compiler/source.cpp src/circuit/circuit.cpp -o bin/hodl

    - name: Run compiled binary
      run: |
        ./bin/hodl --target qasm -o out.qasm data/grover.hodl

  build-macos:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create bin directory
      run: |
        mkdir bin

    - name: Compile C++ file
      run: |
        g++ -std=c++11 src/compiler/source.cpp src/circuit/circuit.cpp -o bin/hodl

    - name: Run compiled binary
      run: |
        ./bin/hodl --target qasm -o out.qasm data/grover.hodl

  # job to publish binaries for all systems
  publish-binaries:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Windows binary
        uses: actions/download-artifact@v2
        with:
          name: windows-binary
          path: bin

      - name: Download Linux binary
        uses: actions/download-artifact@v2
        with:
          name: linux-binary
          path: bin

      - name: Download MacOS binary
        uses: actions/download-artifact@v2
        with:
          name: macos-binary
          path: bin

      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin
          asset_name: ${{ github.event.release.tag_name }}
          asset_content_type: application/octet-stream
