name: HODL Compile, Run and Publish Binaries as Artifacts for Release
on:
  push:
    branches:
      - master
env:
  GITHUB_ACTIONS: true

jobs:

  build-windows:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2.2.0
      
    - name: Create bin directory
      run: |
        mkdir bin

    - name: Compile C++ file
      run: |
        g++ -std=c++11 src/compiler/source.cpp src/circuit/circuit.cpp -o bin/hodl.exe

    - name: Run compiled binary
      run: |
        ./bin/hodl.exe --target qasm -o out.qasm data/grover.hodl

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hodl-windows
        path: bin/hodl.exe  

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create bin directory
      run: |
        mkdir bin

    - name: Compile C++ file
      run: |
        g++ -std=c++11 src/compiler/source.cpp src/circuit/circuit.cpp -o bin/hodl

    - name: Run compiled binary
      run: |
        ./bin/hodl --target qasm -o out.qasm data/grover.hodl

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hodl-linux
        path: bin/hodl

  build-macos:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create bin directory
      run: |
        mkdir bin

    - name: Compile C++ file
      run: |
        g++ -std=c++11 src/compiler/source.cpp src/circuit/circuit.cpp -o bin/hodl

    - name: Run compiled binary
      run: |
        ./bin/hodl --target qasm -o out.qasm data/grover.hodl

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hodl-macos
        path: bin/hodl

  #  create-release:
  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release

      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset Windows
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/hodl.exe
        asset_name: hodl-windows.exe
        asset_content_type: application/octet-stream

    - name: Upload Release Asset Linux
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/hodl
        asset_name: hodl-linux
        asset_content_type: application/octet-stream

    - name: Upload Release Asset MacOS
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/hodl
        asset_name: hodl-macos
        asset_content_type: application/octet-stream
